# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MEEW-Client' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Layout
  pod 'SnapKit', '~> 5.0.0'
  pod 'Then'

  # Pods for Network
  pod 'Alamofire', '~> 5.1' 

  # Pods for alert
  pod 'Firebase/Core'
  pod 'Firebase/Messaging' 

  # Pods for Image caching
  pod 'Kingfisher', '~> 5.0'
end
